name: Build ENPC APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      # 📥 تحميل المشروع
      - name: Checkout repository
        uses: actions/checkout@v4

      # ☕ Java 17
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 🐦 Flutter (نسخة متوافقة مع مشروعك)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.9'
          channel: 'stable'
          cache: true

      # 🔍 تأكد
      - name: Flutter version
        run: flutter --version

      # 📦 تحميل المكتبات
      - name: Install dependencies
        run: flutter pub get

      # 🏗️ بناء APK
      - name: Build APK
        run: |
          flutter build apk \
            --release \
            --split-per-abi \
            --no-shrink \
            --android-skip-build-dependency-validation

      # 📤 رفع APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: enpc-apk
          path: build/app/outputs/flutter-apk/